eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: serviceImpl-feign
  zipkin:
    base-url: http://localhost:9411

