server:
  port: 27075

spring:
  application:
    name: microsvc-gateway
  cloud:
    gateway:
      routes:
        - id: 163
          uri: https://www.163.com/
          order: 9000
          predicates:
          - Path=/163
        # =====================================
        - id: baidu
          uri: https://www.baidu.com
          order: 10000
          predicates:
          - Path=/baidu
